### PR TITLE
Dark mode upload fix

### LINKED ISSUE #268: Dark theme UI bug in uploader widget
The currently-uploaded file is highlighted in such a way that it's unreadable. Screenshot: 

Screen Shot 2020-07-21 at 12 25 57 PM

### PR DESCRIPTION
**Pull request by zachmullen**
Fixes #268 

Light: 

Screen Shot 2020-07-21 at 3 44 46 PM

Dark:

Screen Shot 2020-07-21 at 3 45 00 PM

### CODE REVIEW

File: src/components/Upload.vue [hunk 1]
```diff
@@ -37,7 +37,6 @@
         </v-btn>
         <v-btn
           v-if="!hideStartButton"
-          text="text"
```
Comment (subdavis) [inline src/components/Upload.vue:40]: This is better.
